### PR TITLE
Changed next_node ip6

### PR DESCRIPTION
**Pull request by margau**
For the currently Gluon-Version  fddd:5d16:b5dd::1 is the working next node as in the stable branch.

### CODE REVIEW

**Comment by christf** [comment]
Hi margau, we are curerntly using thebranches dev, test, stable. master is unused. sorry for the mess...

**Comment by margau** [comment]
Okay, for me the master branch was the first point to look for the ffm-next-node adress, so maybe it would be a good idea to correct it anyhow.

**Comment by christf** [comment]
this could be a trigger to re-think our branching strategy - or write it explicitly in a readme file into the master branch.

**Comment by oszilloskop** [comment]
Nothing to do. Wrong branch.

**Pull request closed without merging**
